name: Android CI

on:
  push:
    branches: [ trojan-go ]
  pull_request:
    branches: [ trojan-go ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 #   - name: Grant execute permission for gradlew
 #     run: 
    - name: Build with Gradle
      run: |
            pwd
            echo $ANDROID_HOME
            apt-get install golang-go
            export GOPATH=$HOME/go
            go get -u -d -v golang.org/x/mobile/cmd/gomobile
            go build -a -v golang.org/x/mobile/cmd/gomobile
            go install -v golang.org/x/mobile/cmd/gomobile
            # Make sure we can execute gomobile and gobind directly
            export PATH= /home/runner/work/trojan-go-libs/trojan-go-libs #"$GOPATH/bin:$PATH"
            gh repo clone kangc666/trojan-go-libs
            mv trojan-go-libs src
            cd src
            pushd /path/to/git/repository/just/cloned
            make android
            # prepare gomobile component: gobind
            gomobile init
           
