name: Android CI

on:
  push:
    branches: [ trojan-go ]
  pull_request:
    branches: [ trojan-go ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13.8
 #     Build: 
    - name: Build AAR
      run: |
            pwd
            echo $ANDROID_HOME
            echo -----------
            go get -u -d -v golang.org/x/mobile/cmd/gomobile
            go build -a -v golang.org/x/mobile/cmd/gomobile
            go install -v golang.org/x/mobile/cmd/gomobile
            pushd /home/runner/work/golibs/golibs
            gomobile init
            make android
            ls -l
            
    - name: Upload result for job
      uses: actions/upload-artifact@v1
      with:
          name: AAR
          path: build
         
